### ISSUE TITLE
Teamspeak nickname in use 

### ISSUE THREAD

**Issue by entropylaw** [warlof/seat-teamspeak#21]
```TeamSpeak3_Adapter_ServerQuery_Exception: nickname is already in use in /var/www/seat/vendor/planetteamspeak/ts3-php-framework/libraries/TeamSpeak3/Adapter/ServerQuery/Reply.php:316```

These kinds of errors are starting to pop up out of no where.
Also, removing the user mapping does nothing. Doesn't remove them from teamspeak or remove roles.

**Comment by warlof** [comment]
> Also, removing the user mapping does nothing. Doesn't remove them from teamspeak or remove roles.

Yeah, make sense, since the connector is needing a mapping in order to do anything against someone.
Why would you remove a mapping except in case of some failure ?

---

Regarding your nickname issue, for now, I don't really have any idea of its origin - especially since you said it's start randomly and the last version got 6 month now.

Ensure you don't have some weird stuff like user without any main, or double TS account bind to the same character :/
